#! /usr/bin/env ruby

require "mruby_build_checker/version"
require 'octokit'
require 'tempfile'

module MRuby
  class Build
    CONFIG_PATH = "build_config.rb"

    def initialize(name, &block)
      @name = name
      @blobs = IO.foreach(CONFIG_PATH).to_a
      @client = Octokit::Client.new
      instance_eval(&block)
      Tempfile.create("") do |f|
        f.write @blobs.join("")
        f.close
        system "diff", "-u", CONFIG_PATH, f.path
      end
    end

    def gem(_name = nil, path: nil, github: nil, checksum_hash: nil, branch: 'master')
      if github
        head_sha = @client.commits(github, page: 0, per_page: 1).first['sha']
        if !checksum_hash || head_sha != checksum_hash
          lineno = build_config_lineno - 1
          @blobs[lineno] = %(  conf.gem github: "#{github}", checksum_hash: "#{head_sha}"\n)
        end
      end
    end

    private

    def build_config_lineno
      m = /(^.*):(\d+?):in /.match(caller(2)[0])
      m[2].to_i
    end

    def method_missing(name, *args, &block)
    end
  end
end

load MRuby::Build::CONFIG_PATH
